image: docker:20.10.12

services:
  - docker:20.10.12-dind

stages:
  - build
  - tag

.docker:
  tags:
    - docker
  variables:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_devtools:
  stage: build
  extends: .docker
  only:
    - merge_requests
    - tags
  script:
  - ./build-image.sh flutter-devtools

tag_devtools:
  stage: tag
  extends: .docker
  only:
    - tags
  script:
    - ./tag-image.sh flutter-devtools
